// JDK 21, Gradle 9.5.0

plugins {
    id "java"
    id "io.freefair.lombok" version "9.5.0"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenLocal()
    maven { url "https://maven.aliyun.com/nexus/content/groups/public/" }
    mavenCentral()
}

ext {
    springBootVersion = "3.4.4"
    springKafkaVersion = "3.3.3"
    hutoolVersion = "5.8.44"
    feignVersion = "13.1"
    junitVersion = "4.13.2"
    mockitoVersion = "5.14.1"
}

dependencies {
    // Spring
    implementation group: "org.springframework.boot", name: "spring-boot-starter-logging", version: "${springBootVersion}"
    implementation group: "org.springframework.boot", name: "spring-boot-starter-jdbc", version: "${springBootVersion}"
    implementation group: "org.springframework.boot", name: "spring-boot-starter-web", version: "${springBootVersion}"
    implementation group: "org.springframework.boot", name: "spring-boot-starter-validation", version: "${springBootVersion}"
    implementation group: 'org.springframework.kafka', name: 'spring-kafka', version: "${springKafkaVersion}"
    implementation group: 'io.github.openfeign', name: 'feign-core', version: "${feignVersion}"

    // HuTool
    implementation group: "cn.hutool", name: "hutool-core", version: "${hutoolVersion}"

    // JUnit-4
    testImplementation group: "junit", name: "junit", version: "${junitVersion}"
    // Mock
    testImplementation group: "org.mockito", name: "mockito-core", version: "${mockitoVersion}"
}


tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}